SUBSC_DICT = {
    "pim:led_red_on": {"type": "subsc", "action": "led_red_on"},
    "pim:led_red_off": {"type": "subsc", "action": "led_red_off"},
    "pim:led_blue_on": {"type": "subsc", "action": "led_blue_on"},
    "pim:led_blue_off": {"type": "subsc", "action": "led_blue_off"},
    "pim:buzzer_short": {"type": "subsc", "action": "buzzer_short"},
    "pim:buzzer_long": {"type": "subsc", "action": "buzzer_long"},
    "pim:motor_forward": {"type": "subsc", "action": "motor_forward"},
    "pim:motor_back": {"type": "subsc", "action": "motor_back"},
    "pim:motor_stop": {"type": "subsc", "action": "motor_stop"},
    "pim:motor_left": {"type": "subsc", "action": "motor_left"},
    "pim:motor_right": {"type": "subsc", "action": "motor_right"},
    "pim:servo_left_raise": {"type": "subsc", "action": "servo_left_raise"},
    "pim:servo_left_down": {"type": "subsc", "action": "servo_left_down"},
    "pim:servo_right_raise": {"type": "subsc", "action": "servo_right_raise"},
    "pim:servo_right_down": {"type": "subsc", "action": "servo_right_down"},
    "pim:oled_ip": {"type": "subsc", "action": "oled_ip"},
    "pim:oled_clear": {"type": "subsc", "action": "oled_clear"},
    "pim:oled_room": {"type": "subsc", "action": "oled_room"},
    "pim:oled_graph_r_temp": {"type": "subsc", "action": "oled_graph_r_temp"},
    "pim:oled_graph_r_hum": {"type": "subsc", "action": "oled_graph_r_hum"},
    "pim:oled_graph_r_co2": {"type": "subsc", "action": "oled_graph_r_co2"},
    "pim:oled_veranda": {"type": "subsc", "action": "oled_veranda"},
    "pim:oled_graph_v_temp": {"type": "subsc", "action": "oled_graph_v_temp"},
    "pim:oled_graph_v_hum": {"type": "subsc", "action": "oled_graph_v_hum"},
    "pim:oled_webmanga": {"type": "subsc", "action": "oled_webmanga"},
}
